<Project>
  <!-- https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management -->
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <!-- Avalonia packages -->
    <!-- Important: keep version in sync! -->
    <PackageVersion Include="AngleSharp" Version="1.3.1-beta.491" />
    <PackageVersion Include="Avalonia" Version="11.3.8" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="11.3.8" />
    <PackageVersion Include="Avalonia.Fonts.Inter" Version="11.3.8" />
    <PackageVersion Include="Avalonia.Diagnostics" Version="11.3.8" />
    <PackageVersion Include="Avalonia.Desktop" Version="11.3.8" />
    <PackageVersion Include="Avalonia.iOS" Version="11.3.6" />
    <PackageVersion Include="Avalonia.Browser" Version="11.3.8" />
    <PackageVersion Include="Avalonia.Android" Version="11.3.6" />
    <PackageVersion Include="Castle.Windsor" Version="6.0.0" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageVersion Include="DCore" Version="1.0.17" />
    <PackageVersion Include="DCore.Base" Version="1.0.17" />
    <PackageVersion Include="GraphQL" Version="8.7.0" />
    <PackageVersion Include="GraphX" Version="3.0.0" />
    <PackageVersion Include="Irihi.Ursa" Version="1.13.0" />
    <PackageVersion Include="Irihi.Ursa.Themes.Semi" Version="1.13.0" />
    <PackageVersion Include="Microsoft.Data.Sqlite" Version="10.0.0-rc.2.25502.107" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0-rc.2.25502.107" />
    <PackageVersion Include="NLog" Version="6.0.5" />
    <PackageVersion Include="Notification.Avalonia" Version="2.2.0" />
    <PackageVersion Include="NuGet.DependencyResolver.Core" Version="6.14.0" />
    <PackageVersion Include="QuickGraph" Version="3.6.61119.7" />
    <PackageVersion Include="Semi.Avalonia" Version="11.3.7" />
    <PackageVersion Include="SqlSugarCore" Version="5.1.4.208-preview17" />
    <PackageVersion Include="Stride.GraphX.PCL.Logic" Version="2.4.0" />
    <PackageVersion Include="Stride.GraphX.WPF.Controls" Version="2.4.0" />
    <PackageVersion Include="Xamarin.AndroidX.Core.SplashScreen" Version="1.0.1.15" />
  </ItemGroup>
</Project>