<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AngleSharp" />
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Diagnostics">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Castle.Windsor" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="DCore.Base" />
    <PackageReference Include="GraphQL" />
    <PackageReference Include="GraphX" />
    <PackageReference Include="Irihi.Ursa.Themes.Semi" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="NLog" />
    <PackageReference Include="Notification.Avalonia" />
    <PackageReference Include="NuGet.DependencyResolver.Core" />
    <PackageReference Include="QuickGraph" />
    <PackageReference Include="Semi.Avalonia" />
    <PackageReference Include="SqlSugarCore" />
    <PackageReference Include="Stride.GraphX.PCL.Logic" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Core\Interfaces\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\DataEditView.axaml.cs">
      <DependentUpon>DataEditView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\MindMapView.axaml.cs">
      <DependentUpon>MindMapView.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
